[arquivos]
coord_x = "/home/lunaweeb/Projetos/LunaTools/regressao_linear/arquivos/coord_x3.txt" 
coord_y = "/home/lunaweeb/Projetos/LunaTools/regressao_linear/arquivos/coord_y3.txt"

[grau]
grau = 3

[alvo]
alvo = "/home/lunaweeb/Projetos/LunaTools/regressao_linear/arquivos/gráfico"

[legendas]
titulo = "Gráfico Linear"
eixo_x = "Eixo X"
eixo_y = "Eixo Y"
dados = "Dados"
linha = "Regressão"

[estilo]
cor_dados = "red"
tipo_marca = "circle"
cor_linha = "blue"
tipo_linha = "solid"
estilo = "classic"
