[arquivos]
pasta = "~/Projetos/LunaTools/fitting_polinomial/arquivos/"
arq_coord_x = "coord_x.txt"
arq_coord_y = "coord_y.txt"

[grau]
grau = 3

[alvo]
pasta = "~/Projetos/LunaTools/fitting_polinomial/arquivos/"
nome = "gráfico"

[legendas]
titulo = "Gráfico Linear"
eixo_x = "Eixo X"
eixo_y = "Eixo Y"
dados = "Dados"
linha = "Regressão"

[estilo]
cor_dados = "red"
tipo_marca = "circle"
cor_linha = "blue"
tipo_linha = "solid"
estilo = "classic"
