[colors]
red = "r"
blue = "b"
green = "g"
cyan = "c"
magenta = "m"
yellow = "y"
black = "k"
white = "w"

[markers]
point = "."
pixel = ","
circle = "o"
triangle_down = "v"
triangle_up = "^"
triangle_left = "<"
triangle_right = ">"
square = "s"
pentagon = "p"
star = "*"
hexagon1 = "h"
hexagon2 = "H"
plus = "+"
x = "x"
diamond = "D"
thin_diamond = "d"

[linestyles]
solid = "-"
dashed = "--"
dashdot = "-."
dotted = ":"

[styles]
classic = "classic"
seaborn = "seaborn"
ggplot = "ggplot"
dark_background = "dark_background"
bmh = "bmh"
fast = "fast"
fivethirtyeight = "fivethirtyeight"
grayscale = "grayscale"
seaborn-bright = "seaborn-bright"
seaborn-poster = "seaborn-poster"
seaborn-whitegrid = "seaborn-whitegrid"
