[arquivos]
coord_x = "/home/lunaweeb/Projetos/LunaTools/regressao/arquivos/coord_x.txt" 
coord_y = "/home/lunaweeb/Projetos/LunaTools/regressao/arquivos/coord_y.txt"

[grau]
grau = 3

[alvo]
pasta = "/home/lunaweeb/Projetos/LunaTools/regressao/arquivos/"
nome = "gráfico"

[legendas]
titulo = "Gráfico Linear"
eixo_x = "Eixo X"
eixo_y = "Eixo Y"
dados = "Dados"
linha = "Regressão"

[estilo]
cor_dados = "red"
tipo_marca = "circle"
cor_linha = "blue"
tipo_linha = "solid"
estilo = "classic"
